version: '3.8'
services:
  db:
    image: postgres:15.3
    container_name: eventos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tgmf4
      POSTGRES_DB: proyectocatedra
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: